run E:/MatlabTools/vlfeat-0.9.20-bin/toolbox/vl_setup.m;
clear;
im1 = imread('img1.jpg');
im1 = rgb2gray(im1);
im1 = im2single(im1) ;
[f1,d1] = vl_covdet(im1, 'DoubleImage', true, 'EstimateAffineShape', true, 'PatchRelativeExtent', 10, 'PatchRelativeSmoothing', 1, 'Method', 'DoG', 'verbose') ;

im2 = imread('img2.jpg');
im2 = rgb2gray(im2);
im2 = im2single(im2) ;
[f2,d2] = vl_covdet(im2, 'DoubleImage', true, 'EstimateAffineShape', true, 'PatchRelativeExtent', 10, 'PatchRelativeSmoothing', 1, 'Method', 'DoG', 'verbose') ;

vl_twister('state',0) ;
tree = vl_kdtreebuild(f2,'numTrees',2) ;
[nn, dist2] = vl_kdtreequery(tree, f2, f1, ...
                             'maxNumComparisons', 100, ...
                             'numNeighbors', 1) ;

% [f,d] = vl_covdet(...
%   im, ...
%   'DoubleImage', true, ...
%   'EstimateAffineShape', true, ...
%   'PatchRelativeExtent', 10, ...
%   'PatchRelativeSmoothing', 1, ...
%   'Method', 'DoG') ; %f:6*n_points,d:128*n_points