cc_binary(
  name = "motion_area_detection_server",
  srcs = [
    "server.cc",
  ],
  deps = [
    "//base/common/BUILD:base",
    "//mmu/similiar/vision/motion_area_detect/BUILD:motion_area_detect_lib",
    "//mmu/online_service/protos/BUILD:video_edge_detection",
  ],
)
